add html file
1v4n4/Responsive-web-page pull request #1
Opened 2021-03-29 12:32 UTC by safafa

Html skeleton

2021-03-30 20:07 UTC, christianotieno requested changes
## Changes Required ♻️ 

Hello @safafa & @1v4n4 👋🏾 

Congratulations on submitting your `Building with Responsive Design - Milestone 1` project. 
The code is clean and well maintained. Before we proceed, we need to make sure nothing is messed up. Let's observe the following changes and improve on the highlighted areas below 👇🏾 

## Changes
- [ ] Improve the general layout on a large screen.
- [ ] Improve the README
- [ ] Improve the footer

### Happy coding 💻 
#### Christian Otieno (CR)

2021-03-30 20:07 UTC, christianotieno commented on README.md
> +https://1v4n4.github.io/Responsive-web-page/
## Improve the `README`
- [ ] We currently do need to have the name of the authors listed in the `README` and a screenshot to have a descriptive `README`. The format can also be improved further. Kindly use this [template](https://github.com/microverseinc/readme-template) as an inspiration.

2021-03-30 20:07 UTC, christianotieno commented on index.html
> +<!DOCTYPE html>
## Improve the general layout
- [ ] We currently do have all the sections of the page covering the entire view width of the page. This shouldn't be so. We do need to, however, have only the header, the three main articles and the footer covering the full width of the page. the `Latest funding` section ought to be centred properly. Kindly fix this.

|[Source Page](https://perma.cc/M5ZV-Q2D6)|[Clone Page](https://1v4n4.github.io/Responsive-web-page/)|
|:--:|:--:|
|![tnw](https://user-images.githubusercontent.com/22345961/113048559-59629480-91ab-11eb-841f-28a2729052af.png)|![tnw-clone](https://user-images.githubusercontent.com/22345961/113048599-64b5c000-91ab-11eb-8e87-c2870a74f88c.png)|

2021-03-30 20:07 UTC, christianotieno commented on index.html
> +                            <img class="small-icon" src="img/tnw.png" alt="tnw-logo">
## Code implementation details
- [ ] Ensure the logo has a link (a tag).

2021-03-30 20:07 UTC, christianotieno commented on index.html
> +                                <img src="img/magnifying_glass30x30.png" alt="magnifier-icon">
## Code implementation details
- [ ] Ensure the search button(icon) is also a link.

2021-03-30 20:07 UTC, christianotieno commented on index.html
> +        <footer class="cflex">
## Improve the footer
- [ ] Be mindful of how the social icons have been styled. 
- [ ] Some images are also not loading in this section. Do you mind fixing them,?

|[Source Page](https://perma.cc/M5ZV-Q2D6)|[Clone Page](https://1v4n4.github.io/Responsive-web-page/)|
|:--:|:--:|
|![footer](https://user-images.githubusercontent.com/22345961/113048974-ca09b100-91ab-11eb-857a-e698b809840d.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/113048988-cece6500-91ab-11eb-87b3-f4acaa77c0ee.png)|

2021-03-31 12:23 UTC, Berabjesus requested changes
## Status: CHANGES REQUIRED  :warning: :construction: 
Hi @safafa and @1v4n4. Great progress! Awesome README :100: ! Good job with the changes! :tada: We are almost there. We, however, do have a few changes to carry out before we proceed (see review comment).

**For this project, we have to make sure nothing is messed up, especially in the header and footer. Per the previous review, you have one last thing to work on** 
## changes
- [ ] Improving the footer. 

**Please take a look at the comments below and work on them accordingly.** 
### ❗ Remember you only have one more review left

**When you have made the specified changes, please submit another code review. Thank you!** 
**If you have any questions, let me know by leaving a comment here and mentioning me. 
I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-03-31 12:23 UTC, Berabjesus commented on css/index.css
> +  }
## Improve the footer
The problem with the footer links seems to originate here. On a screen size greater than 1024 the `.socials` class defaults to 10% of the screen size, take the appropriate measure to allow the footer links to be displayed and spaced correctly.

2021-03-31 12:23 UTC, Berabjesus commented on css/index.css
> +}
- [x] [OPTIONAL] No need to use `border-color: rgba(0, 0, 0, 0.363);` if you you are going to use `border: none;` on the next line.
- [x]  [OPTIONAL]  for `border-radius: 50%` the height and width should be equal for a proper circle.

2021-03-31 12:23 UTC, Berabjesus commented on index.html
> +                </div>
## Improve the footer styles:- the social media icons are still not styled properly.

- [ ] Give the appropriate width and height for the social media links so the footer links match the (original website)[https://perma.cc/M5ZV-Q2D6]. 
- [ ] match the appropriate background color of the website for these links.
- [ ] Links should give an impression that they can be clicked. As you can see in the (Source Page)[https://perma.cc/M5ZV-Q2D6] the links change the cursor type when a user hovers over them.

2021-03-31 15:08 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @safafa @1v4n4, good job on your TNW's clone🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 
![Well done team](https://user-images.githubusercontent.com/60631456/113166500-1088fb00-9200-11eb-8eb3-b6bc71def46a.gif)

[ OPTIONAL ]

- You missed the logo in the 768px breakpoint, add it to the header
- Improve the layout of the content in the last section (latest funding round), use padding and margin to fix it.

Now you can merge this branch 🚀 

You can contact me on slack if you have any questions, just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

2021-04-01 09:54 UTC, merged